// Declarations for static image imports (`import light from "…/sun-01.svg"`).
//
// Next normally supplies these through `next-env.d.ts`, but that file is
// generated by `next dev` / `next build` and is gitignored, so a clean checkout
// — CI — typechecks without it and every image import fails with TS2307. This
// references Next's own declarations rather than restating them, so the types
// stay whatever the installed Next says they are.
/// <reference types="next/image-types/global" />

export {};
